default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: voca
  password: note
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: vocanote

test:
  <<: *default
  database: vocanote

production:
  <<: *default
  database: vocanote
  username: 1234
  password: 1234
