default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: vocanote_development

test:
  <<: *default
  database: vocanote_test

production:
  <<: *default
  database: vocanote_production
  username: 1234
  password: 1234
